// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        // Use web config as a fallback for desktop until dedicated Windows
        // FirebaseOptions are generated by FlutterFire CLI.
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfziugRUTb6CfwbzJG9QUns_SxojmuwOo',
    appId: '1:762221062157:android:a804bfca11befefc68cd44',
    messagingSenderId: '762221062157',
    projectId: 'inventory-manager-d70ea',
    storageBucket: 'inventory-manager-d70ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLLh2-snBoJfp6rJL-CGykOK0QJTr6xs',
    appId: '1:762221062157:ios:c7e20e922aded33868cd44',
    messagingSenderId: '762221062157',
    projectId: 'inventory-manager-d70ea',
    storageBucket: 'inventory-manager-d70ea.firebasestorage.app',
    androidClientId:
        '762221062157-nceu16kv3dnnt9a5hie7bu3cs8vultpm.apps.googleusercontent.com',
    iosClientId:
        '762221062157-g9mf8c8akl966vqdnkqh63o7ofa8o5nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManage',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsE3qXc8TmfbiJ6dr8bZ0nZuJsNSiqwM4',
    appId: '1:762221062157:web:8aa17cc66fac065e68cd44',
    messagingSenderId: '762221062157',
    projectId: 'inventory-manager-d70ea',
    authDomain: 'inventory-manager-d70ea.firebaseapp.com',
    storageBucket: 'inventory-manager-d70ea.firebasestorage.app',
    measurementId: 'G-4PR82DYTHQ',
  );
}
